# Étape 1 : Utiliser une image de base avec Java 21
FROM openjdk:17-jdk-slim AS build

# Étape 2 : Définir le répertoire travail
WORKDIR /app

# Étape 3 : Copier le fichier pom.xml et le fichier de dépendances
COPY pom.xml .

# Installer les dépendances
RUN mvn dependency:go-offline

# Étape 4 : Copier le code source de l'application
COPY src ./src

# Étape 5 : Construire l'application
RUN mvn package -DskipTests

# Étape 6 : Étape finale : exécuter le JAR
FROM openjdk:21-jdk-slim
VOLUME /tmp
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]